---
driver:
  name: docker
  use_sudo: false
  privileged: true
  username: root
  volume:
    - /var/run/docker.sock:/docker.sock
  cap_add:
    - sys_admin
  disable_upstart: false
  provision_command:
    - echo 'L /run/docker.sock - - - - /docker.sock' > /etc/tmpfiles.d/docker.conf
sudo: false
provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X stable 2017.7.4
  log_level: info
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - '*.pyc'
    - __pycache__
    - .bundle
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - README.rst
    - .travis.yml
  state_top:
    base:
      "*":
        - git.salt
        - python.pyzmq
  pillars:
    top.sls:
      base:
        "*":
          - jenkins
    jenkins.sls:
      test_git_url: git://github.com/saltstack/salt.git
      test_git_commit: 2018.3
      tornado:
        version: '==5.0.2'
      pyzmq:
        version: '==17.0.0'
platforms:
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd
suites:
  - name: py2
